import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

import '../../core/utils/result.dart';
import '../../data/local/database/app_database.dart';
import '../../data/local/tables/welds_table.dart';
import '../../data/local/tables/welding_standards_table.dart';
import '../../data/local/tables/welding_parameters_table.dart';
import '../../data/repositories/weld_parameters_repository.dart';
import '../../services/welding/pipe_spec.dart';
import '../../services/welding/welding_table.dart';
import '../../services/welding/welding_table_generator.dart';
import '../../workflow/welding_phase.dart';

/// Immutable form state for the weld setup screen.
class WeldSetupState {
  const WeldSetupState({
    // Selector lists (loaded from local DB)
    this.standards = const [],
    this.availableDiameters = const [],
    this.availableSdrRatings = const [],

    // User selections
    this.selectedProjectId,
    this.selectedMachineId,
    this.pipeMaterial,
    this.pipeDiameterMm,
    this.sdrRating,
    this.selectedStandardId,
    this.ambientTemperature,
    this.notes,

    // Machine hydraulics (loaded when machine is selected)
    this.machineHydraulicAreaMm2,
    this.dragPressureBar = 0.0,

    // Result of parameter lookup
    this.matchedParameters,
    this.lookupError,

    // True when parameters were generated locally rather than loaded from DB
    this.parametersFromFallback = false,

    // Computed welding table (machine gauge pressures)
    this.weldingTable,

    // Submission
    this.isSubmitting = false,
    this.submitError,
    this.createdWeldId,
    this.createdPhases,
  });

  final List<WeldingStandardRecord> standards;
  final List<double> availableDiameters;
  final List<String> availableSdrRatings;

  final String? selectedProjectId;
  final String? selectedMachineId;
  final String? pipeMaterial;
  final double? pipeDiameterMm;
  final String? sdrRating;
  final String? selectedStandardId;
  final double? ambientTemperature;
  final String? notes;

  /// Hydraulic cylinder area of the selected machine [mm²].
  /// Null when the machine record does not have this value yet.
  final double? machineHydraulicAreaMm2;

  /// Drag pressure measured by the operator before welding [bar].
  /// Defaults to 0 (no drag) when not entered.
  final double dragPressureBar;

  final WeldingParameterRecord? matchedParameters;
  final String? lookupError;

  /// True when [matchedParameters] was generated by the offline fallback engine
  /// rather than loaded from the local database.  When true the UI shows a
  /// "Parameters generated automatically — verify with standard" warning.
  final bool parametersFromFallback;

  /// Fully computed welding table with machine gauge pressures.
  /// Null until all inputs (pipe, machine, parameters) are resolved.
  final WeldingTable? weldingTable;

  final bool isSubmitting;
  final String? submitError;
  final String? createdWeldId;
  final List<PhaseParameters>? createdPhases;

  /// True when machine has a hydraulic cylinder area entered.
  bool get machineHasCylinderArea =>
      machineHydraulicAreaMm2 != null && machineHydraulicAreaMm2! > 0;

  bool get isReadyToStart =>
      selectedProjectId != null &&
      selectedMachineId != null &&
      pipeMaterial != null &&
      pipeDiameterMm != null &&
      sdrRating != null &&
      selectedStandardId != null &&
      matchedParameters != null &&
      !isSubmitting;

  bool get parametersResolved => matchedParameters != null;

  WeldSetupState copyWith({
    List<WeldingStandardRecord>? standards,
    List<double>? availableDiameters,
    List<String>? availableSdrRatings,
    String? selectedProjectId,
    String? selectedMachineId,
    String? pipeMaterial,
    double? pipeDiameterMm,
    String? sdrRating,
    String? selectedStandardId,
    double? ambientTemperature,
    String? notes,
    double? machineHydraulicAreaMm2,
    double? dragPressureBar,
    WeldingParameterRecord? matchedParameters,
    bool? parametersFromFallback,
    String? lookupError,
    WeldingTable? weldingTable,
    bool? isSubmitting,
    String? submitError,
    String? createdWeldId,
    List<PhaseParameters>? createdPhases,
    bool clearDiameter = false,
    bool clearSdr = false,
    bool clearParams = false,
    bool clearTable = false,
    bool clearLookupError = false,
    bool clearSubmitError = false,
    bool clearCreatedWeld = false,
    bool clearMachineHydraulics = false,
  }) =>
      WeldSetupState(
        standards: standards ?? this.standards,
        availableDiameters:
            clearDiameter ? [] : (availableDiameters ?? this.availableDiameters),
        availableSdrRatings:
            clearSdr ? [] : (availableSdrRatings ?? this.availableSdrRatings),
        selectedProjectId: selectedProjectId ?? this.selectedProjectId,
        selectedMachineId: selectedMachineId ?? this.selectedMachineId,
        pipeMaterial: pipeMaterial ?? this.pipeMaterial,
        pipeDiameterMm:
            clearDiameter ? null : (pipeDiameterMm ?? this.pipeDiameterMm),
        sdrRating: (clearDiameter || clearSdr)
            ? null
            : (sdrRating ?? this.sdrRating),
        selectedStandardId: selectedStandardId ?? this.selectedStandardId,
        ambientTemperature: ambientTemperature ?? this.ambientTemperature,
        notes: notes ?? this.notes,
        machineHydraulicAreaMm2: clearMachineHydraulics
            ? null
            : (machineHydraulicAreaMm2 ?? this.machineHydraulicAreaMm2),
        dragPressureBar: dragPressureBar ?? this.dragPressureBar,
        matchedParameters:
            clearParams ? null : (matchedParameters ?? this.matchedParameters),
        parametersFromFallback: clearParams
            ? false
            : (parametersFromFallback ?? this.parametersFromFallback),
        lookupError:
            clearLookupError ? null : (lookupError ?? this.lookupError),
        weldingTable: (clearTable || clearParams)
            ? null
            : (weldingTable ?? this.weldingTable),
        isSubmitting: isSubmitting ?? this.isSubmitting,
        submitError:
            clearSubmitError ? null : (submitError ?? this.submitError),
        createdWeldId:
            clearCreatedWeld ? null : (createdWeldId ?? this.createdWeldId),
        createdPhases:
            clearCreatedWeld ? null : (createdPhases ?? this.createdPhases),
      );
}

/// Manages all state transitions for the WeldSetupScreen:
///   1. Loading standards from DB
///   2. Cascading dropdown updates (diameter → SDR → parameter lookup)
///   3. Loading machine hydraulic cylinder area on machine selection
///   4. Computing machine gauge pressures via [WeldingTableGenerator]
///   5. Creating the weld record in SQLite on "Start Weld"
class WeldSetupNotifier extends StateNotifier<WeldSetupState> {
  WeldSetupNotifier({
    required this.paramsRepo,
    required this.db,
  }) : super(const WeldSetupState()) {
    _loadStandards();
  }

  final WeldParametersRepository paramsRepo;
  final AppDatabase db;

  // ── Initialisation ────────────────────────────────────────────────────────

  Future<void> _loadStandards() async {
    final result = await paramsRepo.getStandards();
    result.when(
      success: (standards) => state = state.copyWith(standards: standards),
      failure: (_) {},
    );
  }

  // ── Selector handlers ─────────────────────────────────────────────────────

  void selectProject(String projectId) =>
      state = state.copyWith(selectedProjectId: projectId);

  /// Selects the machine and loads its hydraulic cylinder area from the DB.
  Future<void> selectMachine(String machineId) async {
    state = state.copyWith(
      selectedMachineId: machineId,
      clearMachineHydraulics: true,
      clearTable: true,
    );
    final machine = await db.machinesDao.getById(machineId);
    if (machine != null) {
      state = state.copyWith(
        machineHydraulicAreaMm2: machine.hydraulicCylinderAreaMm2,
      );
    }
    _regenerateWeldingTable();
  }

  Future<void> selectStandard(String standardId) async {
    state = state.copyWith(
      selectedStandardId: standardId,
      clearDiameter: true,
      clearSdr: true,
      clearParams: true,
      clearTable: true,
    );
    await _refreshDiameters();
  }

  Future<void> selectMaterial(String material) async {
    state = state.copyWith(
      pipeMaterial: material,
      clearDiameter: true,
      clearSdr: true,
      clearParams: true,
      clearTable: true,
    );
    await _refreshDiameters();
  }

  Future<void> selectDiameter(double diameterMm) async {
    state = state.copyWith(
      pipeDiameterMm: diameterMm,
      clearSdr: true,
      clearParams: true,
      clearTable: true,
    );
    await _refreshSdrRatings();
  }

  Future<void> selectSdr(String sdr) async {
    state = state.copyWith(sdrRating: sdr, clearParams: true, clearTable: true);
    await _lookupParameters();
  }

  void setAmbientTemperature(double temp) =>
      state = state.copyWith(ambientTemperature: temp);

  void setNotes(String notes) => state = state.copyWith(notes: notes);

  /// Updates the measured drag pressure and recomputes machine gauge pressures.
  void setDragPressure(double bar) {
    state = state.copyWith(dragPressureBar: bar, clearTable: true);
    _regenerateWeldingTable();
  }

  // ── Cascading refresh ─────────────────────────────────────────────────────

  Future<void> _refreshDiameters() async {
    final standardId = state.selectedStandardId;
    final material = state.pipeMaterial;
    if (standardId == null || material == null) return;

    final result = await paramsRepo.getAvailableDiameters(
      standardId: standardId,
      pipeMaterial: material,
    );
    result.when(
      success: (diameters) =>
          state = state.copyWith(availableDiameters: diameters),
      failure: (_) {},
    );
  }

  Future<void> _refreshSdrRatings() async {
    final standardId = state.selectedStandardId;
    final material = state.pipeMaterial;
    final diameter = state.pipeDiameterMm;
    if (standardId == null || material == null || diameter == null) return;

    final result = await paramsRepo.getAvailableSdrRatings(
      standardId: standardId,
      pipeMaterial: material,
      pipeDiameterMm: diameter,
    );
    result.when(
      success: (sdrs) => state = state.copyWith(availableSdrRatings: sdrs),
      failure: (_) {},
    );
  }

  Future<void> _lookupParameters() async {
    final standardId = state.selectedStandardId;
    final material = state.pipeMaterial;
    final diameter = state.pipeDiameterMm;
    final sdr = state.sdrRating;
    if (standardId == null ||
        material == null ||
        diameter == null ||
        sdr == null) return;

    state = state.copyWith(clearLookupError: true);

    final result = await paramsRepo.lookupParameters(
      standardId: standardId,
      pipeMaterial: material,
      pipeDiameterMm: diameter,
      sdrRating: sdr,
    );
    result.when(
      success: (params) {
        state = state.copyWith(
          matchedParameters: params,
          parametersFromFallback: false,
        );
        _regenerateWeldingTable();
      },
      failure: (_) {
        // No DB record for this pipe spec — generate parameters offline using
        // the built-in standard engine.  The UI shows a warning badge so the
        // welder knows these were computed, not loaded from certified data.
        final companion = WeldingTableGenerator.generateFallbackForStandard(
          standardId: standardId,
          pipeDiameterMm: diameter,
          sdrRating: sdr,
          pipeMaterial: material,
          hydraulicCylinderAreaMm2: state.machineHydraulicAreaMm2,
          dragPressureBar: state.dragPressureBar,
        );
        final fallbackRecord = WeldingTableGenerator.companionToRecord(
          companion: companion,
          id: 'fallback-$standardId-$material-${diameter.toStringAsFixed(0)}-$sdr',
          standardId: standardId,
        );
        state = state.copyWith(
          matchedParameters: fallbackRecord,
          parametersFromFallback: true,
          clearLookupError: true,
        );
        _regenerateWeldingTable();
      },
    );
  }

  // ── Welding table generation ───────────────────────────────────────────────

  /// Recomputes [WeldingTable] whenever any input changes.
  ///
  /// Silently does nothing if the required inputs are not yet available.
  void _regenerateWeldingTable() {
    final params = state.matchedParameters;
    final diameter = state.pipeDiameterMm;
    final sdr = state.sdrRating;
    final material = state.pipeMaterial;

    if (params == null || diameter == null || sdr == null || material == null) {
      return;
    }

    final sdrRatio = double.tryParse(sdr);
    if (sdrRatio == null || sdrRatio <= 1) return;

    final standard = state.standards
        .where((s) => s.id == state.selectedStandardId)
        .firstOrNull;
    final weldType = standard?.weldType ?? 'butt_fusion';

    final pipeSpec = PipeSpec(
      outerDiameterMm: diameter,
      sdrRatio: sdrRatio,
      material: material,
    );

    final machineSpec = MachineSpec(
      hydraulicCylinderAreaMm2: state.machineHydraulicAreaMm2,
      dragPressureBar: state.dragPressureBar,
    );

    final table = WeldingTableGenerator.generate(
      record: params,
      pipeSpec: pipeSpec,
      machineSpec: machineSpec,
      weldType: weldType,
    );

    state = state.copyWith(weldingTable: table);
  }

  // ── Start weld ────────────────────────────────────────────────────────────

  /// Creates a weld record in the local database, builds [PhaseParameters],
  /// and stores the result in state for the calling screen to navigate with.
  ///
  /// If a [WeldingTable] has been computed (machine cylinder area known),
  /// its machine-gauge [PhaseParameters] are used.  Otherwise falls back to
  /// the repository's interfacial-pressure phases.
  Future<void> startWeld() async {
    if (!state.isReadyToStart) return;

    state = state.copyWith(isSubmitting: true, clearSubmitError: true);

    try {
      // 1. Determine weld type from the standard
      final standard = state.standards
          .where((s) => s.id == state.selectedStandardId)
          .firstOrNull;
      final weldType = standard?.weldType ?? 'butt_fusion';

      // 2. Validate ambient temperature
      final params = state.matchedParameters!;
      final ambient = state.ambientTemperature;
      if (ambient != null &&
          (ambient < params.ambientTempMinCelsius ||
              ambient > params.ambientTempMaxCelsius)) {
        state = state.copyWith(
          isSubmitting: false,
          submitError:
              'Ambient temperature ${ambient.toStringAsFixed(1)}°C is outside '
              'the allowed range '
              '(${params.ambientTempMinCelsius}–${params.ambientTempMaxCelsius}°C) '
              'for this standard.',
        );
        return;
      }

      // 3. Placeholder operator id (replaced by real auth in a later sprint)
      const operatorId = 'unknown-operator';

      // 4. Resolve wall thickness for the DB record
      final sdrRatio = double.tryParse(state.sdrRating ?? '');
      final wallThickness = (sdrRatio != null && sdrRatio > 1 && state.pipeDiameterMm != null)
          ? state.pipeDiameterMm! / sdrRatio
          : params.wallThicknessMm;

      // 5. Create local weld record
      final weldId = const Uuid().v4();
      final now = DateTime.now();
      await db.weldsDao.insertWeld(WeldsTableCompanion(
        id: Value(weldId),
        projectId: Value(state.selectedProjectId!),
        machineId: Value(state.selectedMachineId!),
        operatorId: const Value(operatorId),
        weldType: Value(weldType),
        status: const Value('in_progress'),
        pipeMaterial: Value(state.pipeMaterial!),
        pipeDiameter: Value(state.pipeDiameterMm!),
        pipeSdr: Value(state.sdrRating),
        pipeWallThickness: Value(wallThickness),
        ambientTemperature: Value(state.ambientTemperature),
        standardId: Value(state.selectedStandardId),
        standardUsed: Value(standard?.code),
        notes: Value(state.notes),
        startedAt: Value(now),
        createdAt: Value(now),
        updatedAt: Value(now),
        syncStatus: const Value('pending'),
      ));

      // 6. Use machine-gauge phases when available, else interfacial fallback
      final phases = state.weldingTable?.phases ??
          WeldParametersRepository.buildPhaseParameters(params, weldType);

      state = state.copyWith(
        isSubmitting: false,
        createdWeldId: weldId,
        createdPhases: phases,
      );
    } catch (e) {
      state = state.copyWith(
        isSubmitting: false,
        submitError: 'Failed to create weld: ${e.toString()}',
      );
    }
  }

  /// Called after the screen has read [createdWeldId] and navigated away,
  /// so that back-navigation does not trigger re-navigation.
  void resetCreated() {
    state = state.copyWith(clearCreatedWeld: true);
  }
}
