import 'dart:math' as math;
import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'weld_trace_recorder.dart';

/// Generates a PDF welding report as a [Uint8List].
///
/// The report contains:
///   1. Title block — "Welding Report"
///   2. General information table (project, machine, pipe, date)
///   3. Curve summary (duration, max pressure, average pressure)
///   4. Pressure × time chart (vector line rendering)
///   5. Digital signature block (SHA-256 fingerprint)
///   6. Footer — "Generated by WeldTrace"
///
/// Usage:
/// ```dart
/// final pdfBytes = await WeldReportGenerator.generate(
///   projectName:   'Pipeline P-01',
///   machineName:   'Ritmo Delta 160',
///   diameter:      160,
///   material:      'PE100',
///   sdr:           '11',
///   curve:         recorder.export(),
///   weldSignature: signature,
///   timestamp:     DateTime.now(),
/// );
/// ```
class WeldReportGenerator {
  WeldReportGenerator._();

  /// Generates a PDF report and returns it as raw bytes.
  ///
  /// Handles the empty-curve case gracefully — the chart section will show a
  /// "No data recorded" message.
  static Future<Uint8List> generate({
    required String projectName,
    required String machineName,
    required double diameter,
    required String material,
    required String sdr,
    required List<WeldTracePoint> curve,
    required String weldSignature,
    required DateTime timestamp,
  }) async {
    final pdf = pw.Document(
      author:  'WeldTrace',
      title:   'Welding Report — $projectName',
      creator: 'WeldTrace v1.0',
    );

    // ── Derived statistics ────────────────────────────────────────────────────
    final duration    = curve.isNotEmpty
        ? (curve.last.timeSeconds - curve.first.timeSeconds)
        : 0.0;
    final maxPressure = curve.isNotEmpty
        ? curve.map((p) => p.pressureBar).reduce(math.max)
        : 0.0;
    final avgPressure = curve.isNotEmpty
        ? curve.map((p) => p.pressureBar).reduce((a, b) => a + b) /
              curve.length
        : 0.0;

    final dateStr = DateFormat('dd MMM yyyy HH:mm').format(timestamp);

    // ── Colour palette ────────────────────────────────────────────────────────
    const headerColour = PdfColor.fromInt(0xFF1B3A5C);  // deep navy
    const accentColour = PdfColor.fromInt(0xFF2E7EB8);  // steel blue
    const rowAltColour = PdfColor.fromInt(0xFFF5F7FA);  // light grey

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat:  PdfPageFormat.a4,
          margin:      const pw.EdgeInsets.all(36),
          buildBackground: (context) => pw.Container(
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                left: pw.BorderSide(color: accentColour, width: 4),
              ),
            ),
          ),
        ),
        header: (context) => _buildHeader(headerColour, accentColour),
        footer: (context) => _buildFooter(context, accentColour),
        build: (context) => [
          pw.SizedBox(height: 12),

          // ── General information ─────────────────────────────────────────────
          _sectionTitle('General Information', accentColour),
          pw.SizedBox(height: 6),
          _infoTable(
            rows: [
              ['Project',        projectName],
              ['Machine',        machineName],
              ['Pipe Diameter',  '${diameter.toStringAsFixed(1)} mm'],
              ['Material',       material],
              ['SDR',            sdr],
              ['Date',           dateStr],
            ],
            altColour: rowAltColour,
          ),
          pw.SizedBox(height: 16),

          // ── Curve summary ───────────────────────────────────────────────────
          _sectionTitle('Curve Summary', accentColour),
          pw.SizedBox(height: 6),
          _infoTable(
            rows: [
              ['Duration',          '${duration.toStringAsFixed(1)} s'],
              ['Max Pressure',      '${maxPressure.toStringAsFixed(3)} bar'],
              ['Average Pressure',  '${avgPressure.toStringAsFixed(3)} bar'],
              ['Sample Count',      '${curve.length}'],
            ],
            altColour: rowAltColour,
          ),
          pw.SizedBox(height: 16),

          // ── Pressure × time chart ───────────────────────────────────────────
          _sectionTitle('Pressure × Time Curve', accentColour),
          pw.SizedBox(height: 6),
          _chart(curve, accentColour),
          pw.SizedBox(height: 16),

          // ── Digital signature block ─────────────────────────────────────────
          _sectionTitle('Digital Weld Signature (SHA-256)', accentColour),
          pw.SizedBox(height: 6),
          _signatureBlock(weldSignature, rowAltColour, accentColour),
        ],
      ),
    );

    return pdf.save();
  }

  // ── Section builders ──────────────────────────────────────────────────────

  static pw.Widget _buildHeader(PdfColor headerColour, PdfColor accentColour) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'WELDING REPORT',
              style: pw.TextStyle(
                fontSize:    22,
                fontWeight:  pw.FontWeight.bold,
                color:       headerColour,
              ),
            ),
            pw.Text(
              'WeldTrace',
              style: pw.TextStyle(
                fontSize:  12,
                color:     accentColour,
                fontStyle: pw.FontStyle.italic,
              ),
            ),
          ],
        ),
        pw.Divider(color: accentColour, thickness: 1.5),
      ],
    );
  }

  static pw.Widget _buildFooter(
      pw.Context context, PdfColor accentColour) {
    return pw.Column(
      children: [
        pw.Divider(color: accentColour, thickness: 0.5),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by WeldTrace',
              style: pw.TextStyle(
                fontSize: 8,
                color:    PdfColors.grey600,
              ),
            ),
            pw.Text(
              'Page ${context.pageNumber} / ${context.pagesCount}',
              style: pw.TextStyle(
                fontSize: 8,
                color:    PdfColors.grey600,
              ),
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _sectionTitle(String title, PdfColor accentColour) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 3),
      decoration: pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: accentColour, width: 1),
        ),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize:   12,
          fontWeight: pw.FontWeight.bold,
          color:      accentColour,
        ),
      ),
    );
  }

  static pw.Widget _infoTable({
    required List<List<String>> rows,
    required PdfColor altColour,
  }) {
    return pw.Table(
      columnWidths: {
        0: const pw.FlexColumnWidth(1.8),
        1: const pw.FlexColumnWidth(3),
      },
      children: rows.asMap().entries.map((entry) {
        final isAlt = entry.key.isEven;
        final row   = entry.value;
        return pw.TableRow(
          decoration: isAlt ? pw.BoxDecoration(color: altColour) : null,
          children: row
              .map(
                (cell) => pw.Padding(
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 8, vertical: 4),
                  child: pw.Text(
                    cell,
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ),
              )
              .toList(),
        );
      }).toList(),
    );
  }

  static pw.Widget _chart(
      List<WeldTracePoint> curve, PdfColor accentColour) {
    const chartHeight = 160.0;
    const chartWidth  = 460.0;

    return pw.Container(
      width:  chartWidth,
      height: chartHeight,
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
        color:  PdfColors.white,
      ),
      child: curve.length < 2
          ? pw.Center(
              child: pw.Text(
                'No data recorded',
                style: pw.TextStyle(
                  color:    PdfColors.grey500,
                  fontSize: 9,
                  fontStyle: pw.FontStyle.italic,
                ),
              ),
            )
          : pw.CustomPaint(
              painter: _CurvePainter(curve, accentColour),
              child: pw.SizedBox(width: chartWidth, height: chartHeight),
            ),
    );
  }

  static pw.Widget _signatureBlock(
      String signature, PdfColor bgColour, PdfColor accentColour) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color:  bgColour,
        border: pw.Border.all(color: accentColour),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Weld Signature',
            style: pw.TextStyle(
              fontSize:   9,
              fontWeight: pw.FontWeight.bold,
              color:      accentColour,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            signature,
            style: const pw.TextStyle(fontSize: 8),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'This SHA-256 fingerprint uniquely identifies the weld. '
            'Any modification to the curve data will invalidate this signature.',
            style: pw.TextStyle(
              fontSize:  7,
              color:     PdfColors.grey600,
              fontStyle: pw.FontStyle.italic,
            ),
          ),
        ],
      ),
    );
  }
}

/// Custom painter that renders a pressure × time line chart on a PDF canvas.
///
/// Uses only core [PdfGraphics] primitives (moveTo / lineTo / drawLine /
/// strokePath) which are stable across pdf package 3.x versions.  Text labels
/// are intentionally omitted here — they appear in the wrapping [pw.Container]
/// context via [pw.Text] widgets.
class _CurvePainter extends pw.CustomPainter {
  const _CurvePainter(this.curve, this.lineColour);

  final List<WeldTracePoint> curve;
  final PdfColor lineColour;

  @override
  void paint(PdfGraphics canvas, PdfPoint size) {
    if (curve.length < 2) return;

    // Compute data extents.
    final maxT = curve.map((p) => p.timeSeconds).reduce(math.max);
    final maxP = curve.map((p) => p.pressureBar).reduce(math.max);
    final effectiveMaxT = maxT > 0 ? maxT : 1.0;
    final effectiveMaxP = maxP > 0 ? maxP : 1.0;

    // Margins inside the border box.
    const ml = 8.0;  // left margin  [points]
    const mb = 8.0;  // bottom margin
    final w  = size.x - ml - 4;
    final h  = size.y - mb - 4;

    // Project a WeldTracePoint to PDF canvas coordinates.
    // PDF canvas: origin is bottom-left, y increases upward.
    double cx(WeldTracePoint p) =>
        ml + (p.timeSeconds / effectiveMaxT) * w;
    double cy(WeldTracePoint p) =>
        mb + (p.pressureBar / effectiveMaxP) * h;

    // Draw horizontal grid lines at 25 %, 50 %, 75 % pressure.
    canvas.setStrokeColor(PdfColors.grey300);
    canvas.setLineWidth(0.4);
    for (int i = 1; i <= 3; i++) {
      final y = mb + (i / 4) * h;
      canvas.drawLine(ml, y, ml + w, y);
      canvas.strokePath();
    }

    // Draw the pressure–time curve.
    canvas.setStrokeColor(lineColour);
    canvas.setLineWidth(1.2);
    canvas.moveTo(cx(curve.first), cy(curve.first));
    for (int i = 1; i < curve.length; i++) {
      canvas.lineTo(cx(curve[i]), cy(curve[i]));
    }
    canvas.strokePath();
  }

  @override
  bool shouldRepaint() => false;
}
